sudo: required

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: c
compiler:
  - gcc
  - clang
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Jmw6Ss3cPaQMA1B6h7vvKjQVSgUdYzynP0lFMmhap8oGBqAq7r6qu7KpJdytPSo2tyiB6Nw4C+DbA4UBc+r/gUsN3MXUeQ+wtmTbGtXKF3x/EWRz/3vSto8hOoQOjBo4i7QrMrg0A1O+y2NA2rga/6cltKOYMVwIYz/WAijqyDPRR23oneD/D1JkIMSpwRAlTqp1fFRLw0MYnOlV5Qjr74RU6RF8OdfOPgFwoJ58H0WaCuWwjv/pKQ6CFo/V1UGbOQQpXJ9xPg6eqNeebdV+lFGuKAypBK4uqLaeAJMSdgslBlVdRGNE6UZAgB2Lc8/bTHB6xu+CPEC1tCBRE82OdzCZmXFPTmZ84aT/dnLl5xYoQFh032BR7QC9D21ie3QXSaXtS0kc6y7Rf7QkOJAzSL7sEDlmFkfd2CnsbtiQ6dCt+NLZRkxUJywwm04RYc5sl2aIOHM7k7YHLnIIMFoIYFH/JKC3EQC0J2KGBfOV0TLA0UbNaDvJwYYymId6qYllV3FqHXoP3b5JSecloScBvVBT6+KVnf21T0O5g/61BAHO+3InJAgs6medpvFOuO8GtYjrYbf1vip0AiqBnt3M541LkpvI4iP06TmCJfYvMa+kxb3+nvqK34KlUATCTNeEnfxGMpvQQH+ZxXUwL/MOPNvrPcGdp9uc8ACfd/2Aft0="

addons:
  coverity_scan:

    project:
      name: "mattiaswal/dhcp-helper"
      description: "dhcp-helper | A DHCP relay agent, with option82 support"
    notification_email: lazzer@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make"
    branch_pattern: dev

before_install:
  - docker run --privileged -d --name travis-ci -v $(pwd):/travis ubuntu:xenial tail -f /dev/null
  - docker ps

install:
  - docker exec -t travis-ci bash -c "apt-get update;
    apt-get install -y libnl-3-dev libnl-3-200 libnl-route-3-200 libnl-genl-3-200 libnl-route-3-dev libnl-genl-3-dev libjansson-dev libev-dev build-essential autoconf automake pkg-config clang python-scapy tcpdump iproute2 ruby-ffi openssl"
  - docker exec -t travis-ci bash -c "mv /usr/sbin/tcpdump /usr/local/bin/; ln -s /usr/local/bin/tcpdump /usr/sbin/; gem install travis"
 
script:
  - docker exec -t travis-ci bash -c "cd /travis; ./autogen.sh && ./configure && make && make check"
